name: Build and Release Chrome Extension

permissions:
  contents: write
  packages: write

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Zip
        run: zip -r tread-${{ github.ref_name }}.zip dist/*
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: tread-${{ github.ref_name }}
          path: tread-${{ github.ref_name }}.zip

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: tread-${{ github.ref_name }}
      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: tread-${{ github.ref_name }}.zip
