name: Build and Release Chrome Extension

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Zip
        run: zip -r extension.zip dist/*
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: tread-${{ github.ref_name }}
          path: tread-${{ github.ref_name }}.zip

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: extension
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: tread-${{ github.ref_name }}
          body: tread-${{ github.ref_name }}
          draft: false
          prerelease: false
